mysql:
  dataBase: blogger
  userName: root
  passWord: root
  port: 3306
  driverName: mysql
  host: 127.0.0.1
  log_Level: dev
logger:
  level: info
  prefix: '[Blogger]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: 0.0.0.0
  post: 8080
  env: release
site_info:
  created_at: "2023-10-29"
  title: BloggerRoy
  email: zxd2839182980@163.com
  name: Roy
jwt:
  secret: RoyillEs
  expires: 48
  issuer: blogger
qi_niu:
  enable: "false"
  access_key: emdc5BGx_mwdDuP0VXbZlNnwt8QC_8ZLSCOc84zr
  secret_key: QbrB0ZlRvn1dWl663pO_dNTi17Er711YO3hgNyR7
  bucket: ""
  cdn: XXX
  zone: ""
  size: 5
upload:
  size: 5
  size_avatar: 2
  path: uploads/file
  path_avatar: uploads/avatar
redis:
  ip: 127.0.0.1
  port: 6379
  password: redis
  pool_size: 100
admin:
  username: Roy
  avatar: uploads/avatar/Roy摸鱼.png
  github: ""
  bilibili: ""
